export const dummyEmployees = [
	{
		_id: "1",
		uid: "EMP001",
		firstName: "John",
		middleName: "A.",
		lastName: "Doe",
		email: "john.doe@example.com",
		address: "123 Main Street",
		status: "Active",
		designation: "Software Engineer",
		phoneNumber: "123-456-7890",
	},
	{
		_id: "2",
		uid: "EMP002",
		firstName: "Jane",
		middleName: "",
		lastName: "Smith",
		email: "jane.smith@example.com",
		address: "456 Park Avenue",
		status: "Inactive",
		designation: "Product Manager",
		phoneNumber: "987-654-3210",
	},
	{
		_id: "3",
		uid: "EMP003",
		firstName: "Alice",
		middleName: "M.",
		lastName: "Brown",
		email: "alice.brown@example.com",
		address: "789 Elm Street",
		status: "Active",
		designation: "UX Designer",
		phoneNumber: "555-123-4567",
	}, {
		_id: "3",
		uid: "EMP003",
		firstName: "Alice",
		middleName: "M.",
		lastName: "Brown",
		email: "alice.brown@example.com",
		address: "789 Elm Street",
		status: "Active",
		designation: "UX Designer",
		phoneNumber: "555-123-4567",
	}, {
		_id: "4",
		uid: "EMP004",
		firstName: "Alice",
		middleName: "M.",
		lastName: "Brown",
		email: "alice.brown@example.com",
		address: "789 Elm Street",
		status: "Active",
		designation: "UX Designer",
		phoneNumber: "555-123-4567",
	}, {
		_id: "5",
		uid: "EMP005",
		firstName: "Alice",
		middleName: "M.",
		lastName: "Brown",
		email: "alice.brown@example.com",
		address: "789 Elm Street",
		status: "Active",
		designation: "UX Designer",
		phoneNumber: "555-123-4567",
	}, {
		_id: "6",
		uid: "EMP006",
		firstName: "Alice",
		middleName: "M.",
		lastName: "Brown",
		email: "alice.brown@example.com",
		address: "789 Elm Street",
		status: "Active",
		designation: "UX Designer",
		phoneNumber: "555-123-4567",
	}, {
		_id: "7",
		uid: "EMP007",
		firstName: "Alice",
		middleName: "M.",
		lastName: "Brown",
		email: "alice.brown@example.com",
		address: "789 Elm Street",
		status: "Active",
		designation: "UX Designer",
		phoneNumber: "555-123-4567",
	}, {
		_id: "8",
		uid: "EMP008",
		firstName: "Alice",
		middleName: "M.",
		lastName: "Brown",
		email: "alice.brown@example.com",
		address: "789 Elm Street",
		status: "Active",
		designation: "UX Designer",
		phoneNumber: "555-123-4567",
	}
];
export const docData = [
	{
		_id: "1",
		uid: "Guarantor Form",
		firstName: "John",
		dateUploaded: "12 February 2024",
		numberofPages: "1",
		size: "578kb",
		address: "123 Main Street",
	},
	{
		_id: "2",
		uid: "Attestation Form",
		firstName: "Jane",
		dateUploaded: "12 February 2024",
		numberofPages: "7",
		size: "200kb",
		address: "456 Park Avenue",

	},
	{
		_id: "3",
		uid: "Offer Letter",
		firstName: "Alice",
		dateUploaded: "12 February 2024",
		numberofPages: "2",
		size: "387kb",
		address: "789 Elm Street",
	}, {
		_id: "4",
		uid: "Deployment Letter",
		firstName: "Alice",
		dateUploaded: "12 February 2024",
		numberofPages: "3",
		size: "387kb",
		address: "789 Elm Street",
	}, {
		_id: "5",
		uid: "Attestation Form",
		firstName: "Alice",
		dateUploaded: "12 February 2024",
		numberofPages: "3",
		size: "150kb",
		address: "789 Elm Street",
	}, {
		_id: "6",
		uid: "Deployment Letter",
		firstName: "Alice",
		dateUploaded: "12 February 2024",
		numberofPages: "4",
		size: "200kb",
		address: "789 Elm Street",
	}, {
		_id: "7",
		uid: "Guarantor Form",
		firstName: "Alice",
		dateUploaded: "12 February 2024",
		numberofPages: "1",
		size: "1mb",
		address: "789 Elm Street",
	}, {
		_id: "8",
		uid: "Offer Letter",
		firstName: "Alice",
		dateUploaded: "12 February 2024",
		numberofPages: "2",
		size: "150kb",
		address: "789 Elm Street",
	}, {
		_id: "9",
		uid: "Termination Letter",
		firstName: "Alice",
		dateUploaded: "12 February 2024",
		numberofPages: "1",
		size: "200kb",
		address: "789 Elm Street",
	},
];

export const attendanceData = [
	{
		_id: "1",
		date: "July 01, 2023",
		checkIn: "Olivia Ike",
		checkOut: "08:28 AM",
		workingHour: "05:28 PM",
		status: "On Time",
	},
	{
		_id: "2",
		date: "July 01, 2023",
		checkIn: "08:28 AM",
		checkOut: "05:28 PM",
		workingHour: "08:02 Hrs",
		status: "On Time",

	},
	{
		_id: "3",
		date: "July 01, 2023",
		checkIn: "08:28 AM",
		checkOut: "05:28 PM",
		workingHour: "08:02 Hrs",
		status: "On Time",
	}, {
		_id: "4",
		date: "July 01, 2023",
		checkIn: "08:28 AM",
		checkOut: "05:28 PM",
		workingHour: "08:02 Hrs",
		status: "On Time",
	}, {
		_id: "5",
		date: "July 01, 2023",
		checkIn: "08:28 AM",
		checkOut: "05:28 PM",
		workingHour: "08:02 Hrs",
		status: "Late",
	}, {
		_id: "6",
		date: "July 01, 2023",
		checkIn: "08:28 AM",
		checkOut: "05:28 PM",
		workingHour: "08:02 Hrs",
		status: "Absent",
	}, {
		_id: "7",
		date: "July 01, 2023",
		checkIn: "08:28 AM",
		checkOut: "05:28 PM",
		workingHour: "08:02 Hrs",
		status: "Late",
	}, {
		_id: "8",
		date: "July 01, 2023",
		checkIn: "08:28 AM",
		checkOut: "05:28 PM",
		workingHour: "08:02 Hrs",
		status: "On Leave",
	}, {
		_id: "9",
		date: "July 01, 2023",
		checkIn: "08:28 AM",
		checkOut: "05:28 PM",
		workingHour: "08:02 Hrs",
		status: "On Leave",
	},
];

export const timeData = [
	{
		_id: "1",
		uid: "EMP-2025-01234",
		firstName: "Olivia Ike",
		checkIn: "08:28 AM",
		checkOut: "05:28 PM",
		totalHour: "08:02 Hrs",
		status: "On Time",
	},
	{
		_id: "2",
		uid: "EMP-2025-01234",
		firstName: "Mary Baker",
		checkIn: "08:28 AM",
		checkOut: "05:28 PM",
		totalHour: "08:02 Hrs",
		status: "On Time",

	},
	{
		_id: "3",
		uid: "EMP-2025-01234",
		firstName: "Lara Stanley",
		checkIn: "08:28 AM",
		checkOut: "05:28 PM",
		totalHour: "08:02 Hrs",
		status: "On Time",
	}, {
		_id: "4",
		uid: "EMP-2025-01234",
		firstName: "Demi Tolu",
		checkIn: "08:28 AM",
		checkOut: "05:28 PM",
		totalHour: "08:02 Hrs",
		status: "On Time",
	}, {
		_id: "5",
		uid: "EMP-2025-01234",
		firstName: "Candice Peter",
		checkIn: "08:28 AM",
		checkOut: "05:28 PM",
		totalHour: "08:02 Hrs",
		status: "Late",
	}, {
		_id: "6",
		uid: "EMP-2025-01234",
		firstName: "Natalie Tom",
		checkIn: "08:28 AM",
		checkOut: "05:28 PM",
		totalHour: "08:02 Hrs",
		status: "Absent",
	}, {
		_id: "7",
		uid: "EMP-2025-01234",
		firstName: "Daramola Caroline",
		checkIn: "08:28 AM",
		checkOut: "05:28 PM",
		totalHour: "08:02 Hrs",
		status: "Late",
	}, {
		_id: "8",
		uid: "EMP-2025-01234",
		firstName: "Otunba Daniel",
		checkIn: "08:28 AM",
		checkOut: "05:28 PM",
		totalHour: "08:02 Hrs",
		status: "On Leave",
	}, {
		_id: "9",
		uid: "EMP-2025-01234",
		firstName: "Andy Lanre",
		checkIn: "08:28 AM",
		checkOut: "05:28 PM",
		totalHour: "08:02 Hrs",
		status: "On Leave",
	},
];

export const evaluationData = [
	{
		_id: "1",
		uid: "EMP-2025-01234",
		role: "Product Designer",
		department: "Finanace",
		manager: "Tomi Sunday",
		overallrating: "4.0",
		action: "View Details",
	},
	{
		_id: "2",
		uid: "EMP-2025-01234",
		role: "Senior Developer",
		department: "Outsourcing",
		manager: "Emeka Ugo",
		overallrating: "2.0",
		action: "View Details",

	},
	{
		_id: "3",
		uid: "EMP-2025-01234",
		role: "Trainer",
		department: "Finanace",
		manager: "Kike Jones",
		overallrating: "4.0",
		action: "View Details",
	}, {
		_id: "4",
		uid: "EMP-2025-01234",
		role: "Senior Developer",
		department: "Admin",
		manager: "Michael John",
		overallrating: "3.0",
		action: "View Details",
	}, {
		_id: "5",
		uid: "EMP-2025-01234",
		role: "Product Designer",
		department: "Finanace",
		manager: "Kike Jones",
		overallrating: "4.0",
		action: "View Details",
	}, {
		_id: "6",
		uid: "EMP-2025-01234",
		role: "Trainer",
		department: "Finanace",
		manager: "Emeka Ugo",
		overallrating: "3.5",
		action: "View Details",
	}, {
		_id: "7",
		uid: "EMP-2025-01234",
		role: "Accountant",
		department: "Sales",
		manager: "Michael John",
		overallrating: "4.0",
		action: "View Details",
	}, {
		_id: "8",
		uid: "EMP-2025-01234",
		role: "Senior Developer",
		department: "IT",
		manager: "Michael John",
		overallrating: "4.0",
		action: "View Details",
	}, {
		_id: "9",
		uid: "EMP-2025-01234",
		role: "Accountant",
		department: "Outsourcing",
		manager: "Tomi Sunday",
		overallrating: "4.0",
		action: "View Details",
	},
];