export const dummyEmployees = [
	{
		_id: "1",
		uid: "EMP001",
		firstName: "John",
		middleName: "A.",
		lastName: "Doe",
		email: "john.doe@example.com",
		address: "123 Main Street",
		status: "Active",
		designation: "Software Engineer",
		phoneNumber: "123-456-7890",
	},
	{
		_id: "2",
		uid: "EMP002",
		firstName: "Jane",
		middleName: "",
		lastName: "Smith",
		email: "jane.smith@example.com",
		address: "456 Park Avenue",
		status: "Inactive",
		designation: "Product Manager",
		phoneNumber: "987-654-3210",
	},
	{
		_id: "3",
		uid: "EMP003",
		firstName: "Alice",
		middleName: "M.",
		lastName: "Brown",
		email: "alice.brown@example.com",
		address: "789 Elm Street",
		status: "Active",
		designation: "UX Designer",
		phoneNumber: "555-123-4567",
	}, {
		_id: "3",
		uid: "EMP003",
		firstName: "Alice",
		middleName: "M.",
		lastName: "Brown",
		email: "alice.brown@example.com",
		address: "789 Elm Street",
		status: "Active",
		designation: "UX Designer",
		phoneNumber: "555-123-4567",
	}, {
		_id: "4",
		uid: "EMP004",
		firstName: "Alice",
		middleName: "M.",
		lastName: "Brown",
		email: "alice.brown@example.com",
		address: "789 Elm Street",
		status: "Active",
		designation: "UX Designer",
		phoneNumber: "555-123-4567",
	}, {
		_id: "5",
		uid: "EMP005",
		firstName: "Alice",
		middleName: "M.",
		lastName: "Brown",
		email: "alice.brown@example.com",
		address: "789 Elm Street",
		status: "Active",
		designation: "UX Designer",
		phoneNumber: "555-123-4567",
	}, {
		_id: "6",
		uid: "EMP006",
		firstName: "Alice",
		middleName: "M.",
		lastName: "Brown",
		email: "alice.brown@example.com",
		address: "789 Elm Street",
		status: "Active",
		designation: "UX Designer",
		phoneNumber: "555-123-4567",
	}, {
		_id: "7",
		uid: "EMP007",
		firstName: "Alice",
		middleName: "M.",
		lastName: "Brown",
		email: "alice.brown@example.com",
		address: "789 Elm Street",
		status: "Active",
		designation: "UX Designer",
		phoneNumber: "555-123-4567",
	}, {
		_id: "8",
		uid: "EMP008",
		firstName: "Alice",
		middleName: "M.",
		lastName: "Brown",
		email: "alice.brown@example.com",
		address: "789 Elm Street",
		status: "Active",
		designation: "UX Designer",
		phoneNumber: "555-123-4567",
	}
];
